package com.iwant2tryhard.hytils.core;

public enum GameTypes {
    SKYBLOCK("sb", "sb", "Skyblock", "skyblock"),
    WARLORDS_CAPTURE_THE_FLAG("warlords_ctf_mini", "wctf", "Warlords: Capture the Flag", "warlords"),
    WARLORDS_DOMINATION("warlords_domination", "wd", "Warlords: Domination", "warlords"),
    WARLORDS_TEAM_DEATHMATCH("warlords_team_deathmatch", "wtd", "Warlords: Team Deathmatch", "warlords"),
    MEGAWALLS_STANDARD("mw_standard", "mws", "Mega Walls: Standard", "megawalls"),
    MEGAWALLS_FACEOFF("mw_face_off", "mwf", "Mega Walls: Faceoff", "megawalls"),
    BLITZ_SOLO("blitz_solo_normal", "btz1", "Blitz: Solo", "blitz"),
    BLITZ_TEAMS("blitz_teams_normal", "btz2", "Blitz: Teams", "blitz"),
    SKYWARS_RANKED("ranked_normal", "swr", "Skywars: Ranked", "skywars"),
    SKYWARS_SOLO_NORMAL("solo_normal", "sw1n", "Skywars: Solo Normal", "skywars"),
    SKYWARS_SOLO_INSANE("solo_insane", "sw1i", "Skywars: Solo Insane", "skywars"),
    SKYWARS_TEAMS_NORMAL("teams_normal", "sq2n", "Skywars: Teams Normal", "skywars"),
    SKYWARS_TEAMS_INSANE("teams_insane", "sw2i", "Skywars: Teams Insane", "skywars"),
    SKYWARS_SOLO_MEGA("mega_normal", "sw1m", "Skywars: Mega Solo", "skywars"),
    SKYWARS_TEAMS_MEGA("mega_doubles", "sw2m", "Skywars: Mega Teams", "skywars"),
    SKYWARS_SOLO_TNTMADNESS("solo_insane_tnt_madness", "sw1tnt", "Skywars: TNT Madness Solo", "skywars"),
    SKYWARS_TEAMS_TNTMADNESS("teams_insane_tnt_madness", "sw2tnt", "Skywars: TNT Madness Teams", "skywars"),
    SKYWARS_SOLO_RUSH("solo_insane_rush", "sw1r", "Skywars: Rush Solo", "skywars"),
    SKYWARS_TEAMS_RUSH("teams_insane_rush", "sw2r", "Skywars: Rush Teams", "skywars"),
    SKYWARS_SOLO_SLIME("solo_insane_slime", "sw1s", "Skywars: Slime Solo", "skywars"),
    SKYWARS_TEAMS_SLIME("teams_insane_slime", "sw2s", "Skywars: Slime Teams", "skywars"),
    SKYWARS_SOLO_LUCKYBLOCKS("solo_insane_lucky", "sw1lb", "Skywars: Lucky Blocks Solo", "skywars"),
    SKYWARS_TEAMS_LUCKYBLOCKS("teams_insane_lucky", "sw2lb", "Skywars: Lucky Blocks Teams", "skywars"),
    TNTGAMES_TNTRUN("tnt_tntrun", "tntrun", "TNT Games: TNT Run", "tntgames"),
    TNTGAMES_PVPRUN("tnt_pvprun", "pvprun", "TNT Games: PVP Run", "tntgames"),
    TNTGAMES_BOWSPLEEF("tnt_bowspleef", "bowspleef", "TNT Games: Bow Spleef", "tntgames"),
    TNTGAMES_TNTTAG("tnt_tntag", "tntag", "TNT Games: TNT Tag", "tntgames"),
    TNTGAMES_TNTWIZARDS("tnt_capture", "wizards", "TNT Games: Wizards", "tntgames"),
    BEDWARS_SOLO("bedwars_eight_one", "bw1", "Bedwars: Solo", "bedwars"),
    BEDWARS_DOUBLES("bedwars_eight_two", "bw2", "Bedwars: Doubles", "bedwars"),
    BEDWARS_TRIPLES("bedwars_four_three", "bw3", "Bedwars: 3v3v3v3", "bedwars"),
    BEDWARS_QUADRUPLES("bedwars_four_four", "bw4", "Bedwars: 4v4v4v4", "bedwars"),
    BEDWARS_QUADS("bedwars_two_four", "bw44", "Bedwars: 4v4", "bedwars"),
    BEDWARS_RUSH_DOUBLES("bedwars_eight_two_rush", "bw2r", "Bedwars: Rush Doubles", "bedwars"),
    BEDWARS_RUSH_QUADRUPLES("bedwars_four_four_rush", "bw4r", "Bedwars: Rush 4v4v4v4", "bedwars"),
    BEDWARS_ULTIMATE_DOUBLES("bedwars_eight_two_ultimate", "bw2u", "Bedwars: Ultimate Doubles", "bedwars"),
    BEDWARS_ULTIMATE_QUADRUPLES("bedwars_four_four_ultimate", "bw4u", "Bedwars: Ultimate 4v4v4v4", "bedwars"),
    BEDWARS_CASTLE("bedwars_castle", "bwc", "Bedwars: Castle 40v40", "bedwars"),
    BEDWARS_VOIDLESS_DOUBLES("bedwars_eight_two_voidless", "bw2v", "Bedwars: Voidless Doubles", "bedwars"),
    BEDWARS_VOIDLESS_QUADRUPLES("bedwars_four_four_voidless", "bw4v", "Bedwars: Voidless 4v4v4v4", "bedwars"),
    BEDWARS_ARMED_DOUBLES("bedwars_eight_two_armed", "bw2a", "Bedwars: Armed Doubles", "bedwars"),
    BEDWARS_ARMED_QUADRUPLES("bedwars_four_four_armed", "bw4a", "Bedwars: Armed 4v4v4v4", "bedwars"),
    BEDWARS_LUCKY_DOUBLES("bedwars_eight_two_lucky", "bw2lb", "Bedwars: Lucky Blocks Doubles", "bedwars"),
    BEDWARS_LUCKY_QUADRUPLES("bedwars_four_four_lucky", "bw4lb", "Bedwars: Locky Blocks 4v4v4v4", "bedwars"),
    PIT("pit", "p", "The Pit", "pit"),
    ARCADE_HOLEINTHEWALL("arcade_hole_in_the_wall", "ahitw", "Arcade: Hole in the Wall", "arcade"),
    ARCADE_FOOTBALL("arcade_soccer", "afb", "Arcade: Football", "arcade"),
    ARCADE_BOUNTYHUNTERS("arcade_bounty_hunters", "abh", "Arcade: Bounty Hunters", "arcade"),
    ARCADE_PIXELPAINTERS("arcade_pixel_painters", "app", "Arcade: Pixel Painters", "arcade"),
    ARCADE_DRAGONWARS("arcade_dragon_wars", "adw", "Arcade: Dragon Wars", "arcade"),
    ARCADE_ENDERSPLEEF("arcade_ender_spleef", "aes", "Arcade: Ender Spleef", "arcade"),
    ARCADE_GALAXYWARS("arcade_starwars", "agw", "Arcade: Galaxy Wars", "arcade"),
    ARCADE_THROWOUT("arcade_throw_out", "ato", "Arcade: Throw Out", "arcade"),
    ARCADE_CREPPERATTACK("arcade_creeper_attack", "aca", "Arcade: Creeper Attack", "arcade"),
    ARCADE_PARTYGAMES("arcade_party_games_1", "aptg", "Arcade: Party Games", "arcade"),
    ARCADE_FARMHUNT("arcade_farm_hunt", "afh", "Arcade: Farm Hunt", "arcade"),
    ARCADE_ZOMBIES_DEADEND("arcade_zombies_dead_end", "azde", "Arcade: Zombies - Dead End", "arcade"),
    ARCADE_ZOMBIES_BADBLOOD("arcade_zombies_bad_blood", "azbb", "Arcade: Zombies - Bad Blood", "arcade"),
    ARCADE_ZOMBIES_ALIENARCADIUM("arcade_zombies_alien_arcadium", "azaa", "Arcade: Zombies - Alien Arcadium", "arcade"),
    ARCADE_HIDEANDSEEK_PROPHUNT("arcade_hide_and_seek_prop_hunt", "ahasph", "Arcade: Hide and Seek - Prop Hunt", "arcade"),
    ARCADE_HIDEANDSEEK_PARTYPOOPER("arcade_hide_and_seek_party_pooper", "ahaspp", "Arcade: Hide and Seek - Party Pooper", "arcade"),
    ARCADE_HYPIXELSAYS("arcade_simon_says", "ahs", "Arcade: Hypixel Says", "arcade"),
    ARCADE_SANTASAYS("arcade_santa_says", "asa", "Arcade: Santa Says", "arcade"),
    ARCADE_MINIWALLS("arcade_mini_walls", "amiw", "Arcade: Mini Walls", "arcade"),
    ARCADE_BLOCKINGDEAD("arcade_day_one", "abd", "Arcade: Blocking Dead", "arcade"),
    ARCADE_CAPTURETHEWOOL("arcade_pvp_ctw", "actw", "Arcade: Capture the Wool", "arcade"),
    COPSANDCRIMS_DEFUSAL("mcgo_normal", "cacd", "Cops and Crims: Defusal", "copsandcrims"),
    COPSANDCRIMS_DEATHMATCH("mcgo_deathmatch", "cacdm", "Cops and Crims: Deathmatch", "copsandcrims"),
    COPSANDCRIMS_DEFUSAL_PARTY("mcgo_normal_party", "cacdp", "Cops and Crims Party: Defusal", "copsandcrims"),
    COPSANDCRIMS_DEATHMATCH_PARTY("mcgo_deathmatch_party", "cacdmp", "Cops and Crims Party: Deathmatch", "copsandcrims"),
    BUILDBATTLE_SOLO("build_battle_solo_normal", "bb1", "Build Battle: Solo", "buildbattle"),
    BUILDBATTLE_TEAMS("build_battle_teams_normal", "bb2", "Build Battle: Teams", "buildbattle"),
    BUILDBATTLE_PRO("build_battle_solo_pro", "bbp", "Build Battle: Pro Solo", "buildbattle"),
    BUILDBATTLE_GUESS("build_battle_guess_the_build", "bbg", "Build Battle: Guess the Build", "buildbattle"),
    UHC_SOLO("uhc_solo", "uhc1", "UHC: Solo", "uhc"),
    UHC_TEAMS("uhc_teams", "uhc2", "UHC: Teams", "uhc"),
    UHC_EVENTS("uhc_events", "uhce", "UHC: Events", "uhc"),
    CLASSIC_VAMPIREZ("vampirez", "cvampz", "Classic: VampireZ", "classic"),
    CLASSIC_QUAKE_SOLO("quake_solo", "cquake1", "Classic: Quake Solo", "classic"),
    CLASSIC_QUAKE_TEAMS("quake_teams", "cquake2", "Classic: Quake Teams", "classic"),
    CLASSIC_PAINTBALL("paintball", "cpb", "Classic: Paintball Warfare", "classic"),
    CLASSIC_ARENA_1("arena_1v1", "cab1", "Classic: Arena Brawl 1v1", "classic"),
    CLASSIC_ARENA_2("arena_2v2", "cab2", "Classic: Arena Brawl 2v2", "classic"),
    CLASSIC_ARENA_4("arena_4v4", "cab4", "Classic: Arena Brawl 4v4", "classic"),
    CLASSIC_WALLS("walls", "cwall", "Classic: The Walls", "classic"),
    CLASSIC_TURBOKARTRACERS("tkr", "ctkr", "Classic: Turbo Kart Racers", "classic"),
    DUELS_SOLO_CLASSIC("duels_classic_duel", "d1c", "Duels: Solo Classic", "duels"),
    DUELS_SOLO_SKYWARS("duels_sw_duel", "d1sw", "Duels: Solo Skywars", "duels"),
    DUELS_DOUBLES_SKYWARS("duels_sw_doubles", "d2sw", "Duels: Doubles Skywars", "duels"),
    DUELS_SOLO_BOW("duels_bow_duel", "d1b", "Duels: Solo Bow", "duels"),
    DUELS_SOLO_UHC("duels_uhc_duel", "d1uhc", "Duels: Solo UHC", "duels"),
    DUELS_DOUBLES_UHC("duels_uhc_doubles", "d2uhc", "Duels: Doubles UHC", "duels"),
    DUELS_TEAMS_UHC("duels_uhc_four", "dtuhc", "Duels: Teams UHC", "duels"),
    DUELS_DEATHMATCH_UHC("duels_uhc_meetup", "dduhc", "Duels: Deathmatch UHC", "duels"),
    DUELS_SOLO_NODEBUFF("duels_potion_duel", "d1ndb", "Duels: Solo NoDebuff", "duels"),
    DUELS_SOLO_COMBO("duels_combo_duel", "d1co", "Duels: Solo Combo", "duels"),
    DUELS_SOLO_POTION("duels_potion_duel", "d1pot", "Duels: Solo Potion", "duels"),
    DUELS_SOLO_OP("duels_op_duel", "d1op", "Duels: Solo OP", "duels"),
    DUELS_DOUBLES_OP("duels_op_doubles", "d2op", "Duels: Doubles OP", "duels"),
    DUELS_SOLO_MEGAWALLS("duels_mw_duel", "d1mw", "Duels: Solo Mega Walls", "duels"),
    DUELS_DOUBLES_MEGAWALLS("duels_mw_doubles", "d2mw", "Duels: Doubles Mega Walls", "duels"),
    DUELS_SOLO_SUMO("duels_sumo_duel", "d1s", "Duels: Solo Sumo", "duels"),
    DUELS_SOLO_BLITZ("duels_blitz_duel", "s1btz", "Duels: Solo Blitz", "duels"),
    DUELS_SOLO_BOWSPLEEF("duels_bowspleef_duel", "d1bow", "Duels: Solo Bow Spleef", "duels"),
    DUELS_1v1_BRIDGE("duels_bridge_duel", "d1bridge", "Duels: Bridge 1v1", "duels"),
    DUELS_2v2_BRIDGE("duels_bridge_doubles", "d2bridge", "Duels: Bridge 2v2", "duels"),
    DUELS_4v4_BRIDGE("duels_bridge_four", "d4bridge", "Duels: Bridge 4v4", "duels"),
    DUELS_2v2v2v2_BRIDGE("duels_bridge_2v2v2v2", "d22bridge", "Duels: Bridge 2v2v2v2", "duels"),
    DUELS_3v3v3v3_BRIDGE("duels_bridge_3v3v3v3", "d33bridge", "Duels: Bridge 3v3v3v3", "duels"),
    SPEEDUHC_SOLO("speed_solo_normal", "suhc1", "Speed UHC: Solo", "speeduhc"),
    SPEEDUHC_TEAMS("speed_team_normal", "suhc2", "Speed UHC: Teams", "speeduhc"),
    SMASHHEROES_SOLO_1v1v1v1("super_smash_solo_normal", "sh11", "Smash Heroes: 1v1v1v1", "smashheroes"),
    SMASHHEROES_TEAMS_2v2("super_smash_2v2_normal", "sh2", "Smash Heroes: Teams 2v2", "smashheroes"),
    SMASHHEROES_TEAMS_2v2v2("super_smash_teams_normal", "sh22", "Smash Heroes: Teams 2v2v2", "smashheroes"),
    SMASHHEROES_SOLO_1v1("super_smash_1v1_normal", "sh1", "Smash Heroes: 1v1", "smashheroes"),
    SMASHHEROES_FRIENDS_1v1v1v1("super_smash_friends_normal", "shf11", "Smash Heroes: Friends 1v1v1v1", "smashheroes"),
    MURDERMYSTERY_CLASSIC("murder_classic", "mmc", "Murder Mystery: Classic", "murdermystery"),
    MURDERMYSTERY_DOUBLEUP("murder_double_up", "mmd", "Murder Mystery: Double Up", "murdermystery"),
    MURDERMYSTERY_ASSASSINS("murder_assassins", "mma", "Murder Mystery: Assassins", "murdermystery"),
    MURDERMYSTERY_INFECTION("murder_infection", "mmi", "Murder Mystery: Infection", "murdermystery"),
    PTTOWERWARS_SOLO("prototype_towerwars_solo", "ptw1", "Tower Wars (Prototype): Solo", "pttowerwars"),
    PTTOWERWARS_TEAMS("prototype_towerwars_team_of_two", "ptw2", "Tower Wars (Prototype): Teams", "pttowerwars"),
    NOT_IN_GAME("", "", "", "");

    public final String command;
    public final String shortCommand;
    public final String userFriendlyName;
    public final String gameGroup;
    GameTypes(String command, String shortCommand, String userFriendlyName, String gameGroup){
        this.command = command;
        this.shortCommand = shortCommand;
        this.userFriendlyName = userFriendlyName;
        this.gameGroup = gameGroup;
    }
}
